version: 0.2

phases:
  install:
    runtime-versions:
        python: 3.7
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/integration_tests
      - pipenv sync
      - pipenv run python runner.py
